-- Labb v1.0 Master Production Database Setup Script
-- Run this ONCE in Supabase Dashboard -> SQL Editor (https://supabase.com/dashboard/project/hsxwsutqpsvrueuohahr/sql/new)

begin;

-- Extensions
create extension if not exists pgcrypto;
create extension if not exists btree_gist;

-- Sequences
create sequence if not exists public.inventory_code_seq start 1;
create sequence if not exists public.container_code_seq start 1;
create sequence if not exists public.po_number_seq start 1;
create sequence if not exists public.equipment_code_seq start 1;
create sequence if not exists public.sample_code_seq start 1;

-- Core Tables
create table if not exists public.labs (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  address text not null default '',
  po_prefix text not null default 'LABB-PO',
  expiry_notice_days integer not null default 90 check (expiry_notice_days between 1 and 3650),
  reorder_horizon_days integer not null default 30 check (reorder_horizon_days between 1 and 3650),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  lab_id uuid not null references public.labs(id) on delete cascade,
  display_name text not null,
  email text,
  role text not null default 'member' check (role in ('admin','member')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists profiles_lab_idx on public.profiles(lab_id);

-- Helper functions
create or replace function public.current_lab_id() returns uuid
language sql stable security definer set search_path=public
as $$ select lab_id from public.profiles where id=(select auth.uid()) and active=true $$;

create or replace function public.current_role() returns text
language sql stable security definer set search_path=public
as $$ select role from public.profiles where id=(select auth.uid()) and active=true $$;

create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path=public
as $$ select coalesce((select public.current_role())='admin',false) $$;

revoke all on function public.current_lab_id() from public;
revoke all on function public.current_role() from public;
revoke all on function public.is_admin() from public;
grant execute on function public.current_lab_id() to authenticated;
grant execute on function public.current_role() to authenticated;
grant execute on function public.is_admin() to authenticated;

-- Inventory & Containers
create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  lab_id uuid not null references public.labs(id) on delete cascade,
  item_code text not null default ('LABB-' || lpad(nextval('public.inventory_code_seq')::text,6,'0')),
  sku text not null default '',
  name text not null,
  category text not null default 'Other',
  cas text,
  formula text,
  grade text,
  manufacturer text not null default '',
  catalogue_number text not null default '',
  unit text not null default 'unit',
  pack_size numeric(18,6) not null default 1 check (pack_size > 0),
  minimum_stock numeric(18,6) not null default 0 check (minimum_stock >= 0),
  reorder_quantity numeric(18,6) not null default 1 check (reorder_quantity >= 0),
  unit_price numeric(18,2) not null default 0 check (unit_price >= 0),
  currency text not null default 'INR',
  storage_location text not null default 'General Store',
  storage_condition text not null default 'Room Temp',
  hazard_class text,
  notes text not null default '',
  current_stock numeric(18,6) not null default 0 check (current_stock >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(lab_id, item_code)
);

create table if not exists public.containers (
  id bigint generated by default as identity primary key,
  lab_id uuid not null references public.labs(id) on delete cascade,
  inventory_id bigint not null references public.inventory_items(id) on delete cascade,
  container_code text not null default ('LOT-' || lpad(nextval('public.container_code_seq')::text,8,'0')),
  lot_number text not null default '',
  sub_location text not null default '',
  initial_quantity numeric(18,6) not null default 0 check (initial_quantity >= 0),
  remaining_quantity numeric(18,6) not null default 0 check (remaining_quantity >= 0),
  unit text not null default 'unit',
  received_date date not null default current_date,
  opened_date date,
  expiry_date date,
  is_depleted boolean not null default false,
  depleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(lab_id, container_code)
);

-- Vendors & Procurement
create table if not exists public.vendors (
  id bigint generated by default as identity primary key,
  lab_id uuid not null references public.labs(id) on delete cascade,
  name text not null,
  contact_person text not null default '',
  email text not null default '',
  phone text not null default '',
  payment_terms text not null default '',
  lead_time_days integer not null default 7 check (lead_time_days >= 0),
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(lab_id, name)
);

create table if not exists public.procurement_requests (
  id bigint generated by default as identity primary key,
  lab_id uuid not null references public.labs(id) on delete cascade,
  requested_by uuid not null references auth.users(id),
  vendor_id bigint references public.vendors(id) on delete set null,
  status text not null default 'Requested' check(status in ('Requested','Approved','Ordered','Partial','Delivered','Delayed','Closed')),
  project_code text not null default 'General',
  justification text not null default '',
  ordered_total numeric(18,2) not null default 0 check (ordered_total >= 0),
  po_number text,
  expected_date date,
  approved_by uuid references auth.users(id),
  approved_at timestamptz,
  approval_note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(lab_id, po_number)
);

create table if not exists public.procurement_items (
  id bigint generated by default as identity primary key,
  lab_id uuid not null references public.labs(id) on delete cascade,
  request_id bigint not null references public.procurement_requests(id) on delete cascade,
  inventory_id bigint not null references public.inventory_items(id) on delete cascade,
  quantity_requested numeric(18,6) not null check (quantity_requested > 0),
  quantity_received numeric(18,6) not null default 0 check (quantity_received >= 0),
  unit_price numeric(18,2) not null default 0 check (unit_price >= 0),
  currency text not null default 'INR',
  created_at timestamptz not null default now()
);

-- Logs & Acknowledgements
create table if not exists public.usage_logs (
  id bigint generated by default as identity primary key,
  lab_id uuid not null references public.labs(id) on delete cascade,
  inventory_id bigint not null references public.inventory_items(id) on delete cascade,
  container_id bigint references public.containers(id) on delete set null,
  user_id uuid not null references auth.users(id),
  quantity_used numeric(18,6) not null check (quantity_used > 0),
  unit text not null default 'unit',
  purpose text not null default '',
  logged_at timestamptz not null default now()
);

create table if not exists public.attachments (
  id bigint generated by default as identity primary key,
  lab_id uuid not null references public.labs(id) on delete cascade,
  entity_type text not null check(entity_type in ('inventory','request','vendor','equipment','sample','service','other')),
  entity_id text not null,
  file_name text not null,
  storage_path text not null,
  file_size bigint not null check (file_size >= 0),
  mime_type text not null default 'application/octet-stream',
  uploaded_by uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  lab_id uuid references public.labs(id) on delete cascade,
  actor_id uuid references auth.users(id),
  action text not null,
  target_type text not null,
  target_id text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.notification_acknowledgements (
  id bigint generated by default as identity primary key,
  lab_id uuid not null references public.labs(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  notification_key text not null,
  acknowledged_at timestamptz not null default now(),
  unique(user_id, notification_key)
);

-- Equipment, Services, Storage & Samples
create table if not exists public.equipment (
 id bigint generated by default as identity primary key,
 lab_id uuid not null references public.labs(id) on delete cascade,
 equipment_code text not null default ('EQ-'||lpad(nextval('public.equipment_code_seq')::text,6,'0')),
 name text not null, model text not null default '', serial_number text not null default '', location text not null default '',
 status text not null default 'AVAILABLE' check(status in ('AVAILABLE','OUT_OF_SERVICE','RETIRED')),
 calibration_due date, maintenance_due date, notes text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(lab_id,equipment_code)
);

create table if not exists public.equipment_bookings (
 id bigint generated by default as identity primary key, lab_id uuid not null references public.labs(id) on delete cascade,
 equipment_id bigint not null references public.equipment(id) on delete cascade, user_id uuid not null references auth.users(id),
 start_at timestamptz not null, end_at timestamptz not null, purpose text not null default '', status text not null default 'CONFIRMED' check(status in ('CONFIRMED','CANCELLED')),
 created_at timestamptz not null default now(), check(end_at>start_at)
);

alter table public.equipment_bookings drop constraint if exists equipment_booking_no_overlap;
alter table public.equipment_bookings add constraint equipment_booking_no_overlap exclude using gist (equipment_id with =, tstzrange(start_at,end_at,'[)') with &&) where (status='CONFIRMED');

create table if not exists public.equipment_service_logs (
 id bigint generated by default as identity primary key, lab_id uuid not null references public.labs(id) on delete cascade,
 equipment_id bigint not null references public.equipment(id) on delete cascade, service_type text not null check(service_type in ('CALIBRATION','MAINTENANCE','REPAIR')),
 serviced_at date not null default current_date, next_due date, provider text not null default '', notes text not null default '', performed_by uuid references auth.users(id), created_at timestamptz not null default now()
);

create table if not exists public.storage_locations (
 id bigint generated by default as identity primary key, lab_id uuid not null references public.labs(id) on delete cascade,
 parent_id bigint references public.storage_locations(id) on delete cascade, name text not null, code text not null default '',
 location_type text not null check(location_type in ('ROOM','FREEZER','SHELF','RACK','BOX')), created_at timestamptz not null default now(), unique(lab_id,code)
);

create table if not exists public.samples (
 id bigint generated by default as identity primary key, lab_id uuid not null references public.labs(id) on delete cascade,
 sample_code text not null default ('SMP-'||lpad(nextval('public.sample_code_seq')::text,7,'0')), name text not null, project text not null default 'General', owner_id uuid references auth.users(id),
 location_id bigint references public.storage_locations(id) on delete set null, slot text not null default '', quantity numeric(18,6) not null default 1 check(quantity>=0), unit text not null default 'vials',
 status text not null default 'ACTIVE' check(status in ('ACTIVE','CONSUMED','DISPOSED','ARCHIVED')), expiry_date date, notes text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(lab_id,sample_code)
);

-- Triggers & Functions
create or replace function public.touch_updated_at() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  new.updated_at = now();
  return new;
end $$;

create or replace function public.audit_change() returns trigger
language plpgsql security definer set search_path=public as $$
declare
  v_lab uuid;
  v_actor uuid := auth.uid();
  v_target_id text;
  v_details jsonb;
begin
  if TG_OP = 'DELETE' then
    v_lab := old.lab_id;
    v_target_id := old.id::text;
    v_details := to_jsonb(old);
  else
    v_lab := new.lab_id;
    v_target_id := new.id::text;
    v_details := to_jsonb(new);
  end if;

  insert into public.audit_logs (lab_id, actor_id, action, target_type, target_id, details)
  values (v_lab, v_actor, TG_OP, TG_TABLE_NAME, v_target_id, v_details);

  return coalesce(new, old);
end $$;

create or replace function public.recalculate_inventory_stock() returns trigger
language plpgsql security definer set search_path=public as $$
declare
  v_inv_id bigint := coalesce(new.inventory_id, old.inventory_id);
  v_lab_id uuid := coalesce(new.lab_id, old.lab_id);
begin
  update public.inventory_items
  set current_stock = coalesce((
    select sum(remaining_quantity) from public.containers
    where inventory_id = v_inv_id and is_depleted = false
  ), 0),
  updated_at = now()
  where id = v_inv_id and lab_id = v_lab_id;
  return coalesce(new, old);
end $$;

drop trigger if exists trg_touch_labs on public.labs;
create trigger trg_touch_labs before update on public.labs for each row execute function public.touch_updated_at();

drop trigger if exists trg_touch_profiles on public.profiles;
create trigger trg_touch_profiles before update on public.profiles for each row execute function public.touch_updated_at();

drop trigger if exists trg_touch_inventory_items on public.inventory_items;
create trigger trg_touch_inventory_items before update on public.inventory_items for each row execute function public.touch_updated_at();

drop trigger if exists trg_touch_containers on public.containers;
create trigger trg_touch_containers before update on public.containers for each row execute function public.touch_updated_at();

drop trigger if exists trg_touch_vendors on public.vendors;
create trigger trg_touch_vendors before update on public.vendors for each row execute function public.touch_updated_at();

drop trigger if exists trg_touch_procurement_requests on public.procurement_requests;
create trigger trg_touch_procurement_requests before update on public.procurement_requests for each row execute function public.touch_updated_at();

drop trigger if exists trg_touch_equipment on public.equipment;
create trigger trg_touch_equipment before update on public.equipment for each row execute function public.touch_updated_at();

drop trigger if exists trg_touch_samples on public.samples;
create trigger trg_touch_samples before update on public.samples for each row execute function public.touch_updated_at();

drop trigger if exists trg_container_stock on public.containers;
create trigger trg_container_stock after insert or update or delete on public.containers
for each row execute function public.recalculate_inventory_stock();

DO $$ declare t text; begin
 foreach t in array array['labs','profiles','inventory_items','containers','vendors','procurement_requests','procurement_items','usage_logs','attachments','equipment','equipment_bookings','equipment_service_logs','storage_locations','samples'] loop
   execute format('drop trigger if exists trg_audit_%I on public.%I',t,t);
   execute format('create trigger trg_audit_%I after insert or update or delete on public.%I for each row execute function public.audit_change()',t,t);
 end loop;
end $$;

-- Enable RLS
alter table public.labs enable row level security;
alter table public.profiles enable row level security;
alter table public.inventory_items enable row level security;
alter table public.containers enable row level security;
alter table public.vendors enable row level security;
alter table public.procurement_requests enable row level security;
alter table public.procurement_items enable row level security;
alter table public.usage_logs enable row level security;
alter table public.attachments enable row level security;
alter table public.audit_logs enable row level security;
alter table public.notification_acknowledgements enable row level security;
alter table public.equipment enable row level security;
alter table public.equipment_bookings enable row level security;
alter table public.equipment_service_logs enable row level security;
alter table public.storage_locations enable row level security;
alter table public.samples enable row level security;

-- Grants
grant select,insert,update,delete on all tables in schema public to authenticated;
grant usage,select on all sequences in schema public to authenticated;

-- Policies
drop policy if exists "users read own lab" on public.labs;
create policy "users read own lab" on public.labs for select to authenticated using (id = (select public.current_lab_id()));

drop policy if exists "admins update own lab" on public.labs;
create policy "admins update own lab" on public.labs for update to authenticated using (id = (select public.current_lab_id()) and (select public.is_admin())) with check (id = (select public.current_lab_id()) and (select public.is_admin()));

drop policy if exists "users read profiles in lab" on public.profiles;
create policy "users read profiles in lab" on public.profiles for select to authenticated using (lab_id = (select public.current_lab_id()));

drop policy if exists "admins update lab profiles" on public.profiles;
create policy "admins update lab profiles" on public.profiles for update to authenticated using (lab_id=(select public.current_lab_id()) and (select public.is_admin())) with check (lab_id=(select public.current_lab_id()) and role in ('admin','member'));

drop policy if exists "users read inventory in lab" on public.inventory_items;
create policy "users read inventory in lab" on public.inventory_items for select to authenticated using (lab_id = (select public.current_lab_id()));

drop policy if exists "admins manage inventory" on public.inventory_items;
create policy "admins manage inventory" on public.inventory_items for all to authenticated using (lab_id = (select public.current_lab_id()) and (select public.is_admin())) with check (lab_id = (select public.current_lab_id()) and (select public.is_admin()));

drop policy if exists "users read containers in lab" on public.containers;
create policy "users read containers in lab" on public.containers for select to authenticated using (lab_id = (select public.current_lab_id()));

drop policy if exists "users read vendors in lab" on public.vendors;
create policy "users read vendors in lab" on public.vendors for select to authenticated using (lab_id = (select public.current_lab_id()));

drop policy if exists "admins manage vendors" on public.vendors;
create policy "admins manage vendors" on public.vendors for all to authenticated using (lab_id = (select public.current_lab_id()) and (select public.is_admin())) with check (lab_id = (select public.current_lab_id()) and (select public.is_admin()));

drop policy if exists "users read requests in lab" on public.procurement_requests;
create policy "users read requests in lab" on public.procurement_requests for select to authenticated using (lab_id = (select public.current_lab_id()));

drop policy if exists "users create requests" on public.procurement_requests;
create policy "users create requests" on public.procurement_requests for insert to authenticated with check (lab_id = (select public.current_lab_id()) and requested_by = (select auth.uid()));

drop policy if exists "users read request items in lab" on public.procurement_items;
create policy "users read request items in lab" on public.procurement_items for select to authenticated using (lab_id = (select public.current_lab_id()));

drop policy if exists "users read usage logs in lab" on public.usage_logs;
create policy "users read usage logs in lab" on public.usage_logs for select to authenticated using (lab_id = (select public.current_lab_id()));

drop policy if exists "users read attachments in lab" on public.attachments;
create policy "users read attachments in lab" on public.attachments for select to authenticated using (lab_id = (select public.current_lab_id()));

drop policy if exists "users upload attachments" on public.attachments;
create policy "users upload attachments" on public.attachments for insert to authenticated with check (lab_id = (select public.current_lab_id()) and uploaded_by = (select auth.uid()));

drop policy if exists "users read audit logs in lab" on public.audit_logs;
create policy "users read audit logs in lab" on public.audit_logs for select to authenticated using (lab_id = (select public.current_lab_id()));

drop policy if exists "users read own notification acknowledgements" on public.notification_acknowledgements;
create policy "users read own notification acknowledgements" on public.notification_acknowledgements for select to authenticated using (lab_id=(select public.current_lab_id()) and user_id=(select auth.uid()));

drop policy if exists "users acknowledge own notifications" on public.notification_acknowledgements;
create policy "users acknowledge own notifications" on public.notification_acknowledgements for insert to authenticated with check (lab_id=(select public.current_lab_id()) and user_id=(select auth.uid()));

drop policy if exists "members read equipment" on public.equipment;
create policy "members read equipment" on public.equipment for select to authenticated using(lab_id=(select public.current_lab_id()));

drop policy if exists "admins add equipment" on public.equipment;
create policy "admins add equipment" on public.equipment for insert to authenticated with check(lab_id=(select public.current_lab_id()) and (select public.is_admin()));

drop policy if exists "members read bookings" on public.equipment_bookings;
create policy "members read bookings" on public.equipment_bookings for select to authenticated using(lab_id=(select public.current_lab_id()));

drop policy if exists "members create own bookings" on public.equipment_bookings;
create policy "members create own bookings" on public.equipment_bookings for insert to authenticated with check(lab_id=(select public.current_lab_id()) and user_id=(select auth.uid()) and exists(select 1 from public.equipment e where e.id=equipment_id and e.lab_id=(select public.current_lab_id()) and e.status='AVAILABLE'));

drop policy if exists "members read service logs" on public.equipment_service_logs;
create policy "members read service logs" on public.equipment_service_logs for select to authenticated using(lab_id=(select public.current_lab_id()));

drop policy if exists "members read storage locations" on public.storage_locations;
create policy "members read storage locations" on public.storage_locations for select to authenticated using(lab_id=(select public.current_lab_id()));

drop policy if exists "members read samples" on public.samples;
create policy "members read samples" on public.samples for select to authenticated using(lab_id=(select public.current_lab_id()));

drop policy if exists "members add samples" on public.samples;
create policy "members add samples" on public.samples for insert to authenticated with check(lab_id=(select public.current_lab_id()) and owner_id=(select auth.uid()) and (location_id is null or exists(select 1 from public.storage_locations l where l.id=location_id and l.lab_id=(select public.current_lab_id()))));

-- Realtime Publication
DO $$ declare t text; begin
 foreach t in array array['labs','profiles','inventory_items','containers','vendors','procurement_requests','procurement_items','usage_logs','attachments','audit_logs','notification_acknowledgements','equipment','equipment_bookings','equipment_service_logs','storage_locations','samples'] loop
   if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename=t) then execute format('alter publication supabase_realtime add table public.%I',t); end if;
 end loop;
end $$;

-- ----------------------------------------------------
-- STEP 2: AUTO-CONFIRM ADMIN EMAILS & BOOTSTRAP PROFILES
-- ----------------------------------------------------

-- Auto-confirm both created Admin user accounts in auth.users
update auth.users
set email_confirmed_at = coalesce(email_confirmed_at, now())
where email in ('siddhant.admin1@labb.org', 'siddhant.admin2@labb.org');

-- Ensure Laboratory record exists & associate Admin profiles
do $$
declare
  v_lab_id uuid;
begin
  select id into v_lab_id from public.labs order by created_at asc limit 1;
  
  if v_lab_id is null then
    insert into public.labs(name, address, po_prefix)
    values ('Labb Research Laboratory', 'Hyderabad, India', 'LABB-PO')
    returning id into v_lab_id;
  end if;

  -- Insert/update Admin 1
  insert into public.profiles(id, lab_id, display_name, email, role, active)
  values (
    '9d77db0c-8b80-487b-bb2e-c0cbc27d5151'::uuid,
    v_lab_id,
    'Siddhant Admin 1',
    'siddhant.admin1@labb.org',
    'admin',
    true
  )
  on conflict (id) do update set
    lab_id = excluded.lab_id,
    display_name = excluded.display_name,
    email = excluded.email,
    role = 'admin',
    active = true;

  -- Insert/update Admin 2
  insert into public.profiles(id, lab_id, display_name, email, role, active)
  values (
    '01985fcd-4f85-4944-8007-44b284ee34b0'::uuid,
    v_lab_id,
    'Siddhant Admin 2',
    'siddhant.admin2@labb.org',
    'admin',
    true
  )
  on conflict (id) do update set
    lab_id = excluded.lab_id,
    display_name = excluded.display_name,
    email = excluded.email,
    role = 'admin',
    active = true;

end $$;

commit;
