-- Labb v0.6: persistent per-user notification acknowledgements
-- Safe to run after the v0.5 schema.

create table if not exists public.notification_acknowledgements (
  id bigint generated by default as identity primary key,
  lab_id uuid not null references public.labs(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  notification_key text not null,
  acknowledged_at timestamptz not null default now(),
  unique(user_id, notification_key)
);
create index if not exists notification_ack_lab_user_idx on public.notification_acknowledgements(lab_id,user_id,acknowledged_at desc);

alter table public.notification_acknowledgements enable row level security;
grant select,insert,delete on public.notification_acknowledgements to authenticated;
grant usage,select on all sequences in schema public to authenticated;

drop policy if exists "users read own notification acknowledgements" on public.notification_acknowledgements;
create policy "users read own notification acknowledgements" on public.notification_acknowledgements for select to authenticated
using (lab_id=(select public.current_lab_id()) and user_id=(select auth.uid()));

drop policy if exists "users acknowledge own notifications" on public.notification_acknowledgements;
create policy "users acknowledge own notifications" on public.notification_acknowledgements for insert to authenticated
with check (lab_id=(select public.current_lab_id()) and user_id=(select auth.uid()));

drop policy if exists "users clear own notification acknowledgements" on public.notification_acknowledgements;
create policy "users clear own notification acknowledgements" on public.notification_acknowledgements for delete to authenticated
using (lab_id=(select public.current_lab_id()) and user_id=(select auth.uid()));

DO $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='notification_acknowledgements') then
    alter publication supabase_realtime add table public.notification_acknowledgements;
  end if;
end $$;
