-- Labb v0.5 Supabase schema
-- Run in Supabase SQL Editor on a NEW project.
-- Security model: authenticated browser clients + PostgreSQL RLS.

create extension if not exists pgcrypto;

create sequence if not exists public.inventory_code_seq start 1;
create sequence if not exists public.container_code_seq start 1;
create sequence if not exists public.po_number_seq start 1;

create table if not exists public.labs (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  address text not null default '',
  po_prefix text not null default 'LABB-PO',
  expiry_notice_days integer not null default 90 check (expiry_notice_days between 1 and 3650),
  reorder_horizon_days integer not null default 30 check (reorder_horizon_days between 1 and 3650),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  lab_id uuid not null references public.labs(id) on delete cascade,
  display_name text not null,
  role text not null default 'member' check (role in ('admin','member')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists profiles_lab_idx on public.profiles(lab_id);

create or replace function public.current_lab_id() returns uuid
language sql stable security definer set search_path=public
as $$ select lab_id from public.profiles where id=(select auth.uid()) $$;
create or replace function public.current_role() returns text
language sql stable security definer set search_path=public
as $$ select role from public.profiles where id=(select auth.uid()) $$;
create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path=public
as $$ select coalesce((select public.current_role())='admin',false) $$;

revoke all on function public.current_lab_id() from public;
revoke all on function public.current_role() from public;
revoke all on function public.is_admin() from public;
grant execute on function public.current_lab_id() to authenticated;
grant execute on function public.current_role() to authenticated;
grant execute on function public.is_admin() to authenticated;

create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  lab_id uuid not null references public.labs(id) on delete cascade,
  item_code text not null default ('LABB-' || lpad(nextval('public.inventory_code_seq')::text,6,'0')),
  sku text not null default '',
  name text not null,
  category text not null default 'Other',
  cas text,
  formula text,
  grade text,
  manufacturer text not null default '',
  catalogue_number text not null default '',
  current_stock numeric(18,6) not null default 0 check (current_stock>=0),
  min_stock numeric(18,6) not null default 0 check (min_stock>=0),
  unit text not null default 'units',
  storage text not null default '',
  expiry_date date,
  project text not null default 'General',
  unit_cost numeric(18,2) not null default 0 check (unit_cost>=0),
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(lab_id,item_code)
);
create index if not exists inventory_lab_idx on public.inventory_items(lab_id);
create index if not exists inventory_sku_idx on public.inventory_items(lab_id,sku);

create table if not exists public.containers (
  id bigint generated by default as identity primary key,
  lab_id uuid not null references public.labs(id) on delete cascade,
  inventory_id bigint not null references public.inventory_items(id) on delete cascade,
  container_code text not null default ('LABC-' || lpad(nextval('public.container_code_seq')::text,7,'0')),
  quantity_initial numeric(18,6) not null check (quantity_initial>=0),
  quantity_remaining numeric(18,6) not null check (quantity_remaining>=0),
  unit text not null,
  lot_number text not null default '',
  received_date date not null default current_date,
  opened_date date,
  expiry_date date,
  storage text not null default '',
  status text not null default 'ACTIVE' check(status in ('ACTIVE','DEPLETED','DISPOSED')),
  source_request_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(lab_id,container_code)
);
create index if not exists containers_lab_inv_idx on public.containers(lab_id,inventory_id);
create index if not exists containers_expiry_idx on public.containers(lab_id,expiry_date);

create table if not exists public.vendors (
  id bigint generated by default as identity primary key,
  lab_id uuid not null references public.labs(id) on delete cascade,
  name text not null,
  contact text not null default '',
  email text not null default '',
  phone text not null default '',
  city text not null default '',
  rating numeric(2,1) check (rating is null or (rating between 0 and 5)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists vendors_lab_idx on public.vendors(lab_id);

create table if not exists public.procurement_requests (
  id bigint generated by default as identity primary key,
  lab_id uuid not null references public.labs(id) on delete cascade,
  requested_by uuid not null references auth.users(id),
  project text not null default 'General',
  needed_by date,
  justification text not null default '',
  status text not null default 'Requested' check(status in ('Requested','Ordered','Partial','Delivered','Delayed','Closed')),
  vendor_id bigint references public.vendors(id),
  po_number text,
  expected_date date,
  ordered_total numeric(18,2) not null default 0,
  invoice_amount numeric(18,2),
  invoice_ref text not null default '',
  payment_status text not null default 'Unpaid',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(lab_id,po_number)
);
create index if not exists procurement_lab_idx on public.procurement_requests(lab_id,status);

create table if not exists public.procurement_items (
  id bigint generated by default as identity primary key,
  lab_id uuid not null references public.labs(id) on delete cascade,
  request_id bigint not null references public.procurement_requests(id) on delete cascade,
  inventory_id bigint not null references public.inventory_items(id),
  quantity numeric(18,6) not null check(quantity>0),
  received_quantity numeric(18,6) not null default 0 check(received_quantity>=0),
  unit text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists procurement_items_request_idx on public.procurement_items(lab_id,request_id);

create table if not exists public.usage_logs (
  id bigint generated by default as identity primary key,
  lab_id uuid not null references public.labs(id) on delete cascade,
  inventory_id bigint not null references public.inventory_items(id),
  item_name text not null,
  quantity numeric(18,6) not null check(quantity>0),
  unit text not null,
  project text not null default '',
  purpose text not null default '',
  parts jsonb not null default '[]'::jsonb,
  used_by uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);
create index if not exists usage_lab_idx on public.usage_logs(lab_id,created_at desc);

create table if not exists public.attachments (
  id bigint generated by default as identity primary key,
  lab_id uuid not null references public.labs(id) on delete cascade,
  entity_type text not null check(entity_type in ('inventory','request','vendor','other')),
  entity_id text not null,
  file_name text not null,
  storage_path text not null unique,
  mime_type text,
  size_bytes bigint,
  uploaded_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now()
);
create index if not exists attachments_lab_entity_idx on public.attachments(lab_id,entity_type,entity_id);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  lab_id uuid not null references public.labs(id) on delete cascade,
  action text not null,
  entity_type text not null,
  entity_id text,
  actor_id uuid,
  actor_email text,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);
create index if not exists audit_lab_time_idx on public.audit_logs(lab_id,created_at desc);

create or replace function public.touch_updated_at() returns trigger
language plpgsql as $$ begin new.updated_at=now(); return new; end $$;

create or replace function public.recalculate_inventory_stock() returns trigger
language plpgsql security definer set search_path=public
as $$
declare v_inventory bigint;
begin
  v_inventory=coalesce(new.inventory_id,old.inventory_id);
  update public.inventory_items i
  set current_stock=coalesce((select sum(c.quantity_remaining) from public.containers c where c.inventory_id=v_inventory and c.status='ACTIVE'),0), updated_at=now()
  where i.id=v_inventory;
  return coalesce(new,old);
end $$;

create or replace function public.audit_change() returns trigger
language plpgsql security definer set search_path=public
as $$
declare r jsonb; v_lab uuid; v_id text;
begin
  r=case when tg_op='DELETE' then to_jsonb(old) else to_jsonb(new) end;
  v_lab=(r->>'lab_id')::uuid;
  v_id=r->>'id';
  insert into public.audit_logs(lab_id,action,entity_type,entity_id,actor_id,actor_email,old_data,new_data)
  values(v_lab,tg_op,tg_table_name,v_id,(select auth.uid()),(select auth.jwt()->>'email'),case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) end,case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) end);
  return coalesce(new,old);
end $$;

-- updated_at triggers
DO $$ declare t text; begin
  foreach t in array array['labs','profiles','inventory_items','containers','vendors','procurement_requests','procurement_items'] loop
    execute format('drop trigger if exists trg_touch_%I on public.%I',t,t);
    execute format('create trigger trg_touch_%I before update on public.%I for each row execute function public.touch_updated_at()',t,t);
  end loop;
end $$;

drop trigger if exists trg_container_stock on public.containers;
create trigger trg_container_stock after insert or update or delete on public.containers for each row execute function public.recalculate_inventory_stock();

-- Server-side audit. Clients cannot directly insert audit rows.
DO $$ declare t text; begin
  foreach t in array array['inventory_items','containers','vendors','procurement_requests','procurement_items','usage_logs','attachments'] loop
    execute format('drop trigger if exists trg_audit_%I on public.%I',t,t);
    execute format('create trigger trg_audit_%I after insert or update or delete on public.%I for each row execute function public.audit_change()',t,t);
  end loop;
end $$;

-- Atomic stock consumption with FEFO behavior.
create or replace function public.consume_inventory(p_inventory_id bigint,p_quantity numeric,p_project text default null,p_purpose text default null,p_container_id bigint default null)
returns jsonb language plpgsql security definer set search_path=public
as $$
declare v_lab uuid=(select public.current_lab_id()); v_item public.inventory_items%rowtype; v_total numeric; v_left numeric=p_quantity; c record; v_take numeric; v_parts jsonb='[]'::jsonb;
begin
  if v_lab is null then raise exception 'Not authenticated'; end if;
  if p_quantity<=0 then raise exception 'Quantity must be positive'; end if;
  select * into v_item from public.inventory_items where id=p_inventory_id and lab_id=v_lab;
  if not found then raise exception 'Inventory item not found'; end if;
  select coalesce(sum(quantity_remaining),0) into v_total from public.containers where inventory_id=p_inventory_id and lab_id=v_lab and status='ACTIVE' and quantity_remaining>0 and (p_container_id is null or id=p_container_id);
  if v_total<p_quantity then raise exception 'Insufficient stock'; end if;
  for c in select * from public.containers where inventory_id=p_inventory_id and lab_id=v_lab and status='ACTIVE' and quantity_remaining>0 and (p_container_id is null or id=p_container_id) order by expiry_date nulls last, created_at for update loop
    exit when v_left<=0;
    v_take=least(v_left,c.quantity_remaining);
    update public.containers set quantity_remaining=quantity_remaining-v_take,status=case when quantity_remaining-v_take<=0 then 'DEPLETED' else status end where id=c.id;
    v_left=v_left-v_take;
    v_parts=v_parts||jsonb_build_array(jsonb_build_object('container_id',c.id,'container_code',c.container_code,'quantity',v_take));
  end loop;
  insert into public.usage_logs(lab_id,inventory_id,item_name,quantity,unit,project,purpose,parts,used_by)
  values(v_lab,v_item.id,v_item.name,p_quantity,v_item.unit,coalesce(p_project,v_item.project,''),coalesce(p_purpose,''),v_parts,(select auth.uid()));
  return v_parts;
end $$;

-- Admin-only stocktake adjustment. Positive differences create a traceable adjustment container;
-- negative differences deplete existing containers FEFO without creating a scientific usage entry.
create or replace function public.adjust_inventory(p_inventory_id bigint,p_new_stock numeric,p_reason text default '')
returns numeric language plpgsql security definer set search_path=public
as $$
declare v_lab uuid=(select public.current_lab_id()); v_item public.inventory_items%rowtype; v_delta numeric; v_left numeric; c record; v_take numeric;
begin
  if not (select public.is_admin()) then raise exception 'Admin required'; end if;
  if p_new_stock<0 then raise exception 'Stock cannot be negative'; end if;
  select * into v_item from public.inventory_items where id=p_inventory_id and lab_id=v_lab for update;
  if not found then raise exception 'Inventory item not found'; end if;
  v_delta=p_new_stock-v_item.current_stock;
  if v_delta>0 then
    insert into public.containers(lab_id,inventory_id,quantity_initial,quantity_remaining,unit,lot_number,received_date,expiry_date,storage,status)
    values(v_lab,v_item.id,v_delta,v_delta,v_item.unit,'ADJUSTMENT-'||to_char(now(),'YYYYMMDD-HH24MISS'),current_date,v_item.expiry_date,v_item.storage,'ACTIVE');
  elsif v_delta<0 then
    v_left=-v_delta;
    for c in select * from public.containers where inventory_id=v_item.id and lab_id=v_lab and status='ACTIVE' and quantity_remaining>0 order by expiry_date nulls last, created_at for update loop
      exit when v_left<=0; v_take=least(v_left,c.quantity_remaining);
      update public.containers set quantity_remaining=quantity_remaining-v_take,status=case when quantity_remaining-v_take<=0 then 'DEPLETED' else status end where id=c.id;
      v_left=v_left-v_take;
    end loop;
  end if;
  insert into public.audit_logs(lab_id,action,entity_type,entity_id,actor_id,actor_email,new_data)
  values(v_lab,'STOCK_ADJUSTMENT','inventory_items',v_item.id::text,(select auth.uid()),(select auth.jwt()->>'email'),jsonb_build_object('new_stock',p_new_stock,'reason',p_reason));
  return p_new_stock;
end $$;

create or replace function public.place_order(p_request_id bigint,p_vendor_id bigint,p_expected_date date,p_ordered_total numeric)
returns public.procurement_requests language plpgsql security definer set search_path=public
as $$
declare v_lab uuid=(select public.current_lab_id()); r public.procurement_requests%rowtype; v_prefix text; v_po text;
begin
  if not (select public.is_admin()) then raise exception 'Admin required'; end if;
  select * into r from public.procurement_requests where id=p_request_id and lab_id=v_lab for update;
  if not found then raise exception 'Request not found'; end if;
  if r.status<>'Requested' then raise exception 'Request is not in Requested status'; end if;
  if not exists(select 1 from public.vendors where id=p_vendor_id and lab_id=v_lab) then raise exception 'Vendor not found'; end if;
  select po_prefix into v_prefix from public.labs where id=v_lab;
  v_po=coalesce(r.po_number,coalesce(v_prefix,'LABB-PO')||'-'||extract(year from current_date)::int||'-'||lpad(nextval('public.po_number_seq')::text,5,'0'));
  update public.procurement_requests set vendor_id=p_vendor_id,expected_date=p_expected_date,ordered_total=coalesce(p_ordered_total,0),po_number=v_po,status='Ordered' where id=p_request_id returning * into r;
  return r;
end $$;

create or replace function public.receive_procurement(p_request_id bigint,p_lines jsonb)
returns public.procurement_requests language plpgsql security definer set search_path=public
as $$
declare v_lab uuid=(select public.current_lab_id()); r public.procurement_requests%rowtype; z jsonb; pi public.procurement_items%rowtype; inv public.inventory_items%rowtype; v_qty numeric;
begin
  if not (select public.is_admin()) then raise exception 'Admin required'; end if;
  select * into r from public.procurement_requests where id=p_request_id and lab_id=v_lab for update;
  if not found then raise exception 'Request not found'; end if;
  if r.status not in ('Ordered','Partial','Delayed') then raise exception 'Request is not receivable'; end if;
  for z in select * from jsonb_array_elements(p_lines) loop
    select * into pi from public.procurement_items where id=(z->>'procurement_item_id')::bigint and request_id=p_request_id and lab_id=v_lab for update;
    if not found then raise exception 'Procurement item not found'; end if;
    v_qty=least(coalesce((z->>'qty')::numeric,0),pi.quantity-pi.received_quantity);
    if v_qty<=0 then continue; end if;
    select * into inv from public.inventory_items where id=pi.inventory_id and lab_id=v_lab;
    update public.procurement_items set received_quantity=received_quantity+v_qty where id=pi.id;
    insert into public.containers(lab_id,inventory_id,quantity_initial,quantity_remaining,unit,lot_number,received_date,expiry_date,storage,status,source_request_id)
    values(v_lab,inv.id,v_qty,v_qty,inv.unit,coalesce(z->>'lot_number',''),current_date,coalesce(nullif(z->>'expiry_date','')::date,inv.expiry_date),inv.storage,'ACTIVE',p_request_id);
  end loop;
  if not exists(select 1 from public.procurement_items where request_id=p_request_id and received_quantity<quantity) then
    update public.procurement_requests set status='Delivered' where id=p_request_id returning * into r;
  else
    update public.procurement_requests set status='Partial' where id=p_request_id returning * into r;
  end if;
  return r;
end $$;

revoke all on function public.consume_inventory(bigint,numeric,text,text,bigint) from public;
revoke all on function public.adjust_inventory(bigint,numeric,text) from public;
revoke all on function public.place_order(bigint,bigint,date,numeric) from public;
revoke all on function public.receive_procurement(bigint,jsonb) from public;
grant execute on function public.consume_inventory(bigint,numeric,text,text,bigint) to authenticated;
grant execute on function public.adjust_inventory(bigint,numeric,text) to authenticated;
grant execute on function public.place_order(bigint,bigint,date,numeric) to authenticated;
grant execute on function public.receive_procurement(bigint,jsonb) to authenticated;

-- RLS
alter table public.labs enable row level security;
alter table public.profiles enable row level security;
alter table public.inventory_items enable row level security;
alter table public.containers enable row level security;
alter table public.vendors enable row level security;
alter table public.procurement_requests enable row level security;
alter table public.procurement_items enable row level security;
alter table public.usage_logs enable row level security;
alter table public.attachments enable row level security;
alter table public.audit_logs enable row level security;

-- Grants expose operations to PostgREST; RLS decides which rows/operations actually succeed.
grant select,update on public.labs to authenticated;
grant select on public.profiles to authenticated;
grant select,insert,update,delete on public.inventory_items to authenticated;
grant select,insert,update,delete on public.containers to authenticated;
grant select,insert,update,delete on public.vendors to authenticated;
grant select,insert,update on public.procurement_requests to authenticated;
grant select,insert,update on public.procurement_items to authenticated;
grant select on public.usage_logs to authenticated;
grant select,insert,delete on public.attachments to authenticated;
grant select on public.audit_logs to authenticated;
grant usage,select on sequence public.inventory_code_seq,public.container_code_seq,public.po_number_seq to authenticated;
grant usage,select on all sequences in schema public to authenticated;

-- Labs
create policy "lab members can read lab" on public.labs for select to authenticated using (id=(select public.current_lab_id()));
create policy "admins can update lab" on public.labs for update to authenticated using (id=(select public.current_lab_id()) and (select public.is_admin())) with check (id=(select public.current_lab_id()) and (select public.is_admin()));
-- Profiles
create policy "members can read profiles in lab" on public.profiles for select to authenticated using (lab_id=(select public.current_lab_id()));
-- Inventory
create policy "members read inventory" on public.inventory_items for select to authenticated using (lab_id=(select public.current_lab_id()));
create policy "admins insert inventory" on public.inventory_items for insert to authenticated with check (lab_id=(select public.current_lab_id()) and (select public.is_admin()));
create policy "admins update inventory" on public.inventory_items for update to authenticated using (lab_id=(select public.current_lab_id()) and (select public.is_admin())) with check (lab_id=(select public.current_lab_id()) and (select public.is_admin()));
create policy "admins delete inventory" on public.inventory_items for delete to authenticated using (lab_id=(select public.current_lab_id()) and (select public.is_admin()));
-- Containers
create policy "members read containers" on public.containers for select to authenticated using (lab_id=(select public.current_lab_id()));
create policy "admins insert containers" on public.containers for insert to authenticated with check (lab_id=(select public.current_lab_id()) and (select public.is_admin()));
create policy "admins update containers" on public.containers for update to authenticated using (lab_id=(select public.current_lab_id()) and (select public.is_admin())) with check (lab_id=(select public.current_lab_id()) and (select public.is_admin()));
create policy "admins delete containers" on public.containers for delete to authenticated using (lab_id=(select public.current_lab_id()) and (select public.is_admin()));
-- Vendors
create policy "members read vendors" on public.vendors for select to authenticated using (lab_id=(select public.current_lab_id()));
create policy "admins insert vendors" on public.vendors for insert to authenticated with check (lab_id=(select public.current_lab_id()) and (select public.is_admin()));
create policy "admins update vendors" on public.vendors for update to authenticated using (lab_id=(select public.current_lab_id()) and (select public.is_admin())) with check (lab_id=(select public.current_lab_id()) and (select public.is_admin()));
create policy "admins delete vendors" on public.vendors for delete to authenticated using (lab_id=(select public.current_lab_id()) and (select public.is_admin()));
-- Requests: all lab users can read; any authenticated lab user can create a request for self; admins update.
create policy "members read requests" on public.procurement_requests for select to authenticated using (lab_id=(select public.current_lab_id()));
create policy "members create own requests" on public.procurement_requests for insert to authenticated with check (lab_id=(select public.current_lab_id()) and requested_by=(select auth.uid()) and status='Requested');
create policy "admins update requests" on public.procurement_requests for update to authenticated using (lab_id=(select public.current_lab_id()) and (select public.is_admin())) with check (lab_id=(select public.current_lab_id()) and (select public.is_admin()));
create policy "members read request items" on public.procurement_items for select to authenticated using (lab_id=(select public.current_lab_id()));
create policy "requester creates request items" on public.procurement_items for insert to authenticated with check (lab_id=(select public.current_lab_id()) and exists(select 1 from public.procurement_requests r where r.id=request_id and r.lab_id=(select public.current_lab_id()) and r.requested_by=(select auth.uid()) and r.status='Requested'));
create policy "admins update request items" on public.procurement_items for update to authenticated using (lab_id=(select public.current_lab_id()) and (select public.is_admin())) with check (lab_id=(select public.current_lab_id()) and (select public.is_admin()));
-- Usage is inserted via secured RPC, clients read lab usage.
create policy "members read usage" on public.usage_logs for select to authenticated using (lab_id=(select public.current_lab_id()));
-- Attachments: authenticated lab users may attach/read; only admins may delete.
create policy "members read attachments" on public.attachments for select to authenticated using (lab_id=(select public.current_lab_id()));
create policy "members add attachments" on public.attachments for insert to authenticated with check (lab_id=(select public.current_lab_id()) and uploaded_by=(select auth.uid()));
create policy "admins delete attachments" on public.attachments for delete to authenticated using (lab_id=(select public.current_lab_id()) and (select public.is_admin()));
-- Audit log is server-written and lab-readable.
create policy "members read audit" on public.audit_logs for select to authenticated using (lab_id=(select public.current_lab_id()));

-- Private Storage bucket.
insert into storage.buckets(id,name,public,file_size_limit) values('labb-documents','labb-documents',false,52428800)
on conflict(id) do update set public=false;

create policy "lab members read documents" on storage.objects for select to authenticated
using (bucket_id='labb-documents' and split_part(name,'/',1)=(select public.current_lab_id())::text);
create policy "lab members upload documents" on storage.objects for insert to authenticated
with check (bucket_id='labb-documents' and split_part(name,'/',1)=(select public.current_lab_id())::text);
create policy "admins update documents" on storage.objects for update to authenticated
using (bucket_id='labb-documents' and split_part(name,'/',1)=(select public.current_lab_id())::text and (select public.is_admin()))
with check (bucket_id='labb-documents' and split_part(name,'/',1)=(select public.current_lab_id())::text and (select public.is_admin()));
create policy "admins delete documents" on storage.objects for delete to authenticated
using (bucket_id='labb-documents' and split_part(name,'/',1)=(select public.current_lab_id())::text and (select public.is_admin()));

-- Add selected tables to Realtime publication if not already present.
DO $$ declare t text; begin
  foreach t in array array['inventory_items','containers','vendors','procurement_requests','procurement_items','usage_logs','attachments'] loop
    if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename=t) then
      execute format('alter publication supabase_realtime add table public.%I',t);
    end if;
  end loop;
end $$;


-- Labb v0.6 notification acknowledgement layer
-- Labb v0.6: persistent per-user notification acknowledgements
-- Safe to run after the v0.5 schema.

create table if not exists public.notification_acknowledgements (
  id bigint generated by default as identity primary key,
  lab_id uuid not null references public.labs(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  notification_key text not null,
  acknowledged_at timestamptz not null default now(),
  unique(user_id, notification_key)
);
create index if not exists notification_ack_lab_user_idx on public.notification_acknowledgements(lab_id,user_id,acknowledged_at desc);

alter table public.notification_acknowledgements enable row level security;
grant select,insert,delete on public.notification_acknowledgements to authenticated;
grant usage,select on all sequences in schema public to authenticated;

drop policy if exists "users read own notification acknowledgements" on public.notification_acknowledgements;
create policy "users read own notification acknowledgements" on public.notification_acknowledgements for select to authenticated
using (lab_id=(select public.current_lab_id()) and user_id=(select auth.uid()));

drop policy if exists "users acknowledge own notifications" on public.notification_acknowledgements;
create policy "users acknowledge own notifications" on public.notification_acknowledgements for insert to authenticated
with check (lab_id=(select public.current_lab_id()) and user_id=(select auth.uid()));

drop policy if exists "users clear own notification acknowledgements" on public.notification_acknowledgements;
create policy "users clear own notification acknowledgements" on public.notification_acknowledgements for delete to authenticated
using (lab_id=(select public.current_lab_id()) and user_id=(select auth.uid()));

DO $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='notification_acknowledgements') then
    alter publication supabase_realtime add table public.notification_acknowledgements;
  end if;
end $$;
